### ISSUE TITLE
The number of video views does not increase.

### ISSUE THREAD

**Issue by esginmurat** [MacWarrior/clipbucket-5.0#108]
Hello dear owner. 

I'm using the most current version on your page. however, the number of video views does not increase.

There are no error messages. I deleted the browser cache. I deleted the website cache. but the result did not change. the number of video views does not increase. There is no error message in the console about this error either. There is also no error message on the php error page related to this error.

Please help me.
Thanks regards,
![increase](https://user-images.githubusercontent.com/17769013/63961461-8879c700-ca99-11e9-9aec-40bb91e7f4d2.png)
![increase2](https://user-images.githubusercontent.com/17769013/63961462-8879c700-ca99-11e9-818a-3d1b38561a43.png)

**Comment by pnemuk** [comment]
you have to change this round line 1029 /includes/functions_video.php 

increment_views_new($vdo['videokey'],'video');
to
increment_views_new($vdo['videoid'],'video');

or use video key instead of video id
round line 2077 /includes/functions.php 

$db->update(tbl("video"),array("views", "last_viewed"),array("|f|views+1",'NOW()')," videoid='$id'");
to
$db->update(tbl("video"),array("views", "last_viewed"),array("|f|views+1",'NOW()')," videokey='$id'");

**Comment by esginmurat** [comment]
@pnemuk Thank you for the response.. 

I found this line. ( increment_views_new($vdo['videokey'],'video'); ) I change it. Looks like it's working. 

Thanks, regards,

**Comment by MacWarrior** [comment]
Hi, 

Thanks @pnemuk 
Issue has been fixed in last commit
