### ISSUE TITLE
Deprecated method.

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-5.0#113]
Hi,

Methods with the same name as their class will not be constructors in a future version of PHP, ClipBucket has a deprecated constructor in /includes/classes/ClipBucket.class.php on line 10

this line must also be fixed
Warning: in_array() expects parameter 2 to be array, bool given in /includes/config.inc.php on line 57

**Comment by MacWarrior** [comment]
Hi,

1) Are you sure you use the latest version, because in Clipbucket.class.php, there is no Clipbucket() function and the constructor seems up to date : function __construct(), line 73 to112 ?

2) When do you get this error ? ; this meens public_pages is empty but it's a static variable
Line 71 in ClipBucket.class.php : var $public_pages = array("signup","view_page");

Best regards,
MacWarrior.

**Comment by pnemuk** [comment]
yes you are absolutely right
was on my side had out of date function.

var $public_pages = array("signup","view_page");
this line was missing on my testing environment.
